# -*- coding: utf-8 -*-
"""score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CdtpHf2eLodZ8GV9rM8zYnEDAvB1qVs
"""

grades = input().split()

grades = [int(i) for i in grades]

average = sum(grades) / len(grades)

print(average)